# This is an example config file which can used as template and modified as needed
# Far too little optimization steps are included here, but can be used to test the installation

# Landscape exploration
#exploration:
value_key: train_loss
weight_key: saddle_train_loss
suggest:
  - unfinished
  - disconnected
  - mst
autoneb:
  # The first cycle should contain all information, subsequent cycles only _differences_ from the previous
  # One dummy cycle to include the initial loss curve in the analysis dict
  - insert:
      name: leave  # do not insert further points, original path should not be changed in this step
    subsample_pivot_count: 9
    spring_constant: inf
    optim:
      nsteps: 1 # only one step for analysis
      clip_grad: 4.0 # optional, but used by default UMAP
      algorithm:
        name: SGD
        lr: 0.000000001   #really small, as this step is not for optimization
        momentum: 0.9

  # CHANGE THE FOLLOWING STEPS ACCORDING TO YOUR NEEDS:

  # optimize original points once (10 steps)
  - insert:
      name: leave  # currently 3 points to optimize (5 total)
    optim:
      nsteps: 10 # small number to allow for many lr changes (optimal would be linear decrease)
      algorithm:
        name: SGD
        lr: 0.05
        momentum: 0.9
  # insert 1 point each time, until 10 points total
  - insert:
      name: highest
      count: 1 # inserts 1 point
      key: dense_train_loss
    optim:
      nsteps: 10 # small number to allow for many lr changes (optimal would be linear decrease)
      algorithm:
        lr: 0.05
  - insert:
      name: highest
      count: 1 # inserts 1 point
      key: dense_train_loss
    optim:
      nsteps: 10 # small number to allow for many lr changes (optimal would be linear decrease)
      algorithm:
        lr: 0.05
  # start learning rate decay
  - insert:
      name: highest
      count: 1 # inserts 1 point
      key: dense_train_loss
    optim:
      algorithm:
        lr: 0.049
  - optim:  # inserts 1 point
      algorithm:
        lr: 0.048
  #- {} # include this to repeat with the same settings
  #- {}