# This config was used to create the t-SNE connection with manually set initial path for the thesis

# Landscape exploration
# exploration:
value_key: train_loss
weight_key: saddle_train_loss
suggest:
  - unfinished
  - disconnected
  - mst
autoneb:
  # The first cycle should contain all information, subsequent cycles only _differences_ from the previous
  # One dummy cycle to include the initial loss curve in the analysis dict
  - insert:
      name: leave  # do not insert further points, as the path is already given
    subsample_pivot_count: 9
    spring_constant: inf
    weight_decay: 0.0 # has to be zero for optimization to work at all
    optim:
      nsteps: 1 #only one step for analysis
      algorithm:
        name: SGD
        lr: 0.000000001   #really small, as this step is not for optimization
        momentum: 0.9
  # once 500 steps with with preconfigured path around rest (6 total)
  - insert:
      name: leave  # do not insert further points, as the path is already given
    optim:
      nsteps: 500
      algorithm:
        name: SGD
        lr: 2860.0   # = 1e+4 / 3.5
        momentum: 0.9
  # 800 steps to get down broader, 11 total
  - insert:
      name: highest
      count: 5
      key: dense_train_loss
    optim:
      nsteps: 800
  # 200 steps to cut peaks, 21 total
  - insert:
      name: highest
      count: 10
      key: dense_train_loss
    optim:
      nsteps: 200
  # 200 steps to cut peaks, 41 total
  - insert:
      name: highest
      count: 20
      key: dense_train_loss
    optim:
      nsteps: 200
  #- {} # same as previous
  #- {}
