# This config was used to create the t-SNE connections for the thesis

# Landscape exploration
# exploration:
value_key: train_loss
weight_key: saddle_train_loss
suggest:
  - unfinished
  - disconnected
  - mst
autoneb:
  # The first cycle should contain all information, subsequent cycles only _differences_ from the previous
  # One dummy cycle to include the initial loss curve in the analysis dict
  - insert:
      name: leave  # do not insert further points, just plot loss
    subsample_pivot_count: 9
    spring_constant: inf
    weight_decay: 0.0 # has to be zero for optimization to work at all
    optim:
      nsteps: 1 #only one step for analysis
      algorithm:
        name: SGD
        lr: 0.000000001   #really small, as this step is not for optimization
        momentum: 0.9
  # once 500 steps with only one (already initialized) center point (3 total)
  - insert:
      name: leave
    optim:
      nsteps: 500
      algorithm:
        name: SGD
        lr: 2860.0   # = 1e+4 / 3.5
        momentum: 0.9
  # 800 steps to get down broader, 5 total
  - insert:
      name: highest
      count: 2
      key: dense_train_loss
    optim:
      nsteps: 800
  # 200 steps to cut peaks, 9 total
  - insert:
      name: highest
      count: 4
      key: dense_train_loss
    optim:
      nsteps: 200
  # 100 steps to cut peaks, 17 total
  - insert:
      name: highest
      count: 8
      key: dense_train_loss
    optim:
      nsteps: 100
  # 100 steps to cut peaks, 33 total
  - insert:
      name: highest
      count: 16
      key: dense_train_loss
    optim:
      nsteps: 100
  #- {} # same as previous
  #- {}
  
